server:
  type: simple
  applicationContextPath: /
  
allowedGrantTypes: 
  - password
  
realm: nehp-rfid-server

debug: true
     
database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: webapp

  # the password
  password: 5FKL0923pyTm4

  # the JDBC URL
  #url: jdbc:mysql://localhost/test
  url: jdbc:mysql://ec2-54-85-61-143.compute-1.amazonaws.com/test

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 3s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false
  
  # Whether or not connections will be validated before being borrowed from the pool. 
  # If the connection fails to validate, it will be dropped from the pool, and another will be borrowed.
  checkConnectionOnBorrow: true
  
  # Whether or not connections will be validated before being added to the pool. 
  # If the connection fails to validate, it won't be added to the pool.
  checkConnectionOnConnect: true
  
  # Whether or not connections will be validated after being returned to the pool. 
  # If the connection fails to validate, it will be dropped from the pool.
  checkConnectionOnReturn: true
  
# Credentials to connect to third-party smtp server for outgoing mail 
email:
	hostName: smtp.gmail.com
	hostPort: 465
	emailAddress: travis.tarr@nehp.com
	emailUser: travis.tarr@nehp.com
	emailPassword: Katie6574